update readme
open-cluster-management/governance-policy-framework pull request #89
Opened 2021-04-10 01:22 UTC by ycao56

2021-04-10 01:22 UTC, ycao56 commented
/hold

2021-04-12 19:35 UTC, dockerymick requested changes

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +- Policy controllers -- Policy engines running on managed cluster to evaluate policy rules distributed by the policy framework and generate results.
I suggest to update "Policy engines running on managed cluster to evaluate policy rules distributed by the policy framework and generate results."

TO 

Policy engines that run on managed clusters to evaluate policy rules distributed by the policy framework and generate results.

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +    - 3rd party
I recommend changing 3rd party to Third-party

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +The `Policy` is the Custom Resource Definition (CRD), created for policy framework controllers to monitor. It acts as a vechical to deliver policies to managed cluster and collect results back to hub
Update vechical to **vehicle**

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +The `Policy` is the Custom Resource Definition (CRD), created for policy framework controllers to monitor. It acts as a vechical to deliver policies to managed cluster and collect results back to hub
...collect results to send to the hub cluster

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +```yaml
I recommend that you update "This is an example spec of a `Policy` object:" 

TO 

"View the following example specification of a `Policy` object"

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +The `PlacementBinding` CRD is used to bind the `Policy` with `PlacementRule`. Only bound `Policy` will be distributed by policy framework to the managed cluster
Change: The `PlacementBinding` CRD is used to bind the `Policy` with `PlacementRule`.

TO 

The `PlacementBinding` CRD is used to bind the `Policy` with a `PlacementRule`.

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +The `PlacementBinding` CRD is used to bind the `Policy` with `PlacementRule`. Only bound `Policy` will be distributed by policy framework to the managed cluster
Only a bound `Policy` is distributed to a managed cluster by the policy framework.

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +This is an example spec of a `PlacementBinding` object:
View the following example specification of a `PlacementBinding` object:

2021-04-12 19:35 UTC, dockerymick commented on README.md
> +This is an example spec of a `PlacementRule` object:
View the following example specification of a `PlacementRule` object:

2021-04-13 18:46 UTC, ycao56 commented
all done. merging it

2021-04-13 19:05 UTC, merged